#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local REMOTE_DEPENDENCIES_URL="https://raw.githubusercontent.com/diakitenicolas/utils/master/"

  printf "Bootstrapping to scripts\n"
  mkdir -p "./scripts"

  (
    cd "./scripts"

    curl -q -sSL --max-time 10 -o "./worker" "${REMOTE_DEPENDENCIES_URL}/worker"
    chmod +x "./worker"
    source "./worker" && worker_init "${@}"
  )
}

main "${@:-}"